
on:
  push:
    branches: 
      - master
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: your-app-name   
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  NODE_VERSION: '14.x'
  ARM_STORAGE_ACCOUNT_NAME: tfstorefile 
  RESOURCE_GROUP: terraform

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login via Azure CLI
      uses: azure/login@v1
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: npm install,
      run: |
        npm install -g @angular/cli@latest
        npm install -f

    - name: 'ng build'
      run: | 
              ng build -c=ppd --localize
        
    - name: Upload artifact for deployment job
      run: zip -r dist.zip dist

  # deploy:
  #   permissions:
  #     contents: none
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Development'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #   - name: Download artifact from build job
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: node-app

  #   - name: 'Deploy to Azure WebApp'
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #       package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
